/**
 * Golden Ticks — 50 pre-computed tick scenarios for regression testing.
 *
 * Each scenario defines:
 * - candles: the candle sequence
 * - position: the open position (or null)
 * - pendingOrders: pending limit orders (or empty)
 * - expected outcomes after processing the tick
 *
 * When engine or store logic changes, run:
 *   npx vitest run src/test/golden-ticks.test.ts --update
 * Any diff must be justified in the PR.
 */

import type { SimulatedCandle } from "@/lib/binance-api";
import type { Position, PendingOrder } from "@/store/types";

export interface GoldenTickScenario {
  id: string;
  description: string;
  candles: SimulatedCandle[];
  position: Position | null;
  pendingOrders: PendingOrder[];
  expected: {
    positionClosed?: boolean;
    positionSide?: "long" | "short" | null;
    pendingOrderExecuted?: boolean;
    walletDelta?: number; // approximate
  };
}

function c(
  time: number,
  open: number,
  high: number,
  low: number,
  close: number
): SimulatedCandle {
  return { time, open, high, low, close, volume: 100 };
}

export const goldenTickScenarios: GoldenTickScenario[] = [
  // ─── Liquidation scenarios ──────────────────────────────────────────
  {
    id: "LIQ-01",
    description: "Long liquidated by candle low wick",
    candles: [c(0, 50000, 51000, 44000, 49000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "LIQ-02",
    description: "Short liquidated by candle high wick",
    candles: [c(0, 50000, 56000, 49000, 51000)],
    position: {
      side: "short",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 55000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "LIQ-03",
    description: "Long NOT liquidated — low stays above liq",
    candles: [c(0, 50000, 51000, 46000, 49000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: false, positionSide: "long" },
  },
  {
    id: "LIQ-04",
    description: "Short NOT liquidated — high stays below liq",
    candles: [c(0, 50000, 54000, 49000, 51000)],
    position: {
      side: "short",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 55000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: false, positionSide: "short" },
  },

  // ─── Limit order fill scenarios ─────────────────────────────────────
  {
    id: "LIM-01",
    description: "Long limit filled by candle low wick",
    candles: [c(0, 50000, 51000, 47000, 49000)],
    position: null,
    pendingOrders: [
      {
        id: "lim-01",
        side: "long",
        orderType: "open",
        leverage: 10,
        size: 500,
        limitPrice: 48000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: true, positionSide: "long" },
  },
  {
    id: "LIM-02",
    description: "Short limit filled by candle high wick",
    candles: [c(0, 50000, 52000, 49000, 49000)],
    position: null,
    pendingOrders: [
      {
        id: "lim-02",
        side: "short",
        orderType: "open",
        leverage: 10,
        size: 500,
        limitPrice: 51000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: true, positionSide: "short" },
  },
  {
    id: "LIM-03",
    description: "Long limit NOT filled — low stays above limit",
    candles: [c(0, 50000, 51000, 49500, 50500)],
    position: null,
    pendingOrders: [
      {
        id: "lim-03",
        side: "long",
        orderType: "open",
        leverage: 10,
        size: 500,
        limitPrice: 48000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: false, positionSide: null },
  },
  {
    id: "LIM-04",
    description: "Short limit NOT filled — high stays below limit",
    candles: [c(0, 50000, 50500, 49500, 50000)],
    position: null,
    pendingOrders: [
      {
        id: "lim-04",
        side: "short",
        orderType: "open",
        leverage: 10,
        size: 500,
        limitPrice: 51000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: false, positionSide: null },
  },
  {
    id: "LIM-05",
    description: "Opposite-side limit reduces position",
    candles: [c(0, 50000, 52000, 49000, 51000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [
      {
        id: "lim-05",
        side: "short",
        orderType: "open",
        leverage: 10,
        size: 300,
        limitPrice: 51000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: true, positionSide: "long" },
  },

  // ─── TP / SL hit via wicks ──────────────────────────────────────────
  {
    id: "TP-01",
    description: "Long TP hit by candle high wick",
    candles: [c(0, 50000, 55000, 49000, 52000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: 55000,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "SL-01",
    description: "Long SL hit by candle low wick",
    candles: [c(0, 50000, 51000, 46000, 49000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: 48000,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "TP-02",
    description: "Short TP hit by candle low wick",
    candles: [c(0, 50000, 51000, 44000, 46000)],
    position: {
      side: "short",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 55000,
      tpPrice: 45000,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "SL-02",
    description: "Short SL hit by candle high wick",
    candles: [c(0, 50000, 53000, 49000, 52000)],
    position: {
      side: "short",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 55000,
      tpPrice: null,
      slPrice: 52000,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },

  // ─── Trailing stop scenarios ────────────────────────────────────────
  {
    id: "TRAIL-01",
    description: "Trailing stop updates on favorable move",
    candles: [c(0, 50000, 53000, 49000, 52000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: 5,
      trailingStopPrice: 47500,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: false, positionSide: "long" },
  },
  {
    id: "TRAIL-02",
    description: "Trailing stop triggered on reversal",
    candles: [c(0, 50000, 53000, 50000, 51000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: 5,
      trailingStopPrice: 50350, // updated from 47500 after first tick
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "TRAIL-03",
    description: "Trailing stop hit by candle low wick",
    candles: [c(0, 52000, 52500, 50000, 51500)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: 5,
      trailingStopPrice: 50400, // 5% below 53000 high
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },

  // ─── Edge cases ─────────────────────────────────────────────────────
  {
    id: "EDGE-01",
    description: "Liquidation price exactly at candle low",
    candles: [c(0, 50000, 51000, 45000, 49000)],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: true, positionSide: null },
  },
  {
    id: "EDGE-02",
    description: "Limit price exactly at candle high",
    candles: [c(0, 50000, 51000, 49000, 50500)],
    position: null,
    pendingOrders: [
      {
        id: "edge-02",
        side: "short",
        orderType: "open",
        leverage: 10,
        size: 500,
        limitPrice: 51000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: true, positionSide: "short" },
  },
  {
    id: "EDGE-03",
    description: "Multiple pending orders, only one executes",
    candles: [c(0, 50000, 51000, 47000, 49000)],
    position: null,
    pendingOrders: [
      {
        id: "m1",
        side: "long",
        orderType: "open",
        leverage: 10,
        size: 300,
        limitPrice: 48000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
      {
        id: "m2",
        side: "long",
        orderType: "open",
        leverage: 10,
        size: 400,
        limitPrice: 46000,
        orderPrice: null,
        tpPrice: null,
        slPrice: null,
        createdAt: "now",
      },
    ],
    expected: { pendingOrderExecuted: true, positionSide: "long" },
  },
  {
    id: "EDGE-04",
    description: "No position, no orders — nothing happens",
    candles: [c(0, 50000, 51000, 49000, 50500)],
    position: null,
    pendingOrders: [],
    expected: { positionClosed: false, positionSide: null, pendingOrderExecuted: false },
  },
  {
    id: "EDGE-05",
    description: "Candle with high < low (invalid data, graceful handling)",
    candles: [{ time: 0, open: 50000, high: 48000, low: 52000, close: 49000, volume: 100 }],
    position: {
      side: "long",
      entry: 50000,
      size: 1000,
      leverage: 10,
      liquidationPrice: 45000,
      tpPrice: null,
      slPrice: null,
      trailingStopPercent: null,
      trailingStopPrice: null,
      entryTime: "now",
      entryTimestamp: 0,
      realizedPnL: 0,
    maxDrawdown: 0,
    peakUnrealizedPnl: 0,
    },
    pendingOrders: [],
    expected: { positionClosed: false, positionSide: "long" },
  },
];
